package proyectoprogra1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

public class Juego3 extends javax.swing.JFrame {

    String Figura = "";
    String Ruta;
    long tiempo1;
    long tiempo2;

    public Juego3() {
        initComponents();
        jButtonANADIR.setEnabled(false);
        jPanelAPROBADO.setVisible(false);
        tiempo1 = System.currentTimeMillis();
        for (long i = 0; i <= 100000; i++) {
            continue;
        }
        String DatosUsuario;
        try {
            BufferedReader bf = new BufferedReader(new FileReader("C:\\Users\\felix\\Documents\\DatosUsuario.txt"));
            DatosUsuario = bf.readLine();
            DatosUsuario.replaceAll("Etapa 2", "Etapa 3");
            PrintWriter writer = new PrintWriter("C:\\Users\\felix\\Documents\\DatosUsuario.txt", "UTF-8");
            writer.print(DatosUsuario);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Validar() {
        if (jTextFieldPALABRA.getText().isBlank()
                || jTextAreaSIGNIFICADO.getText().isBlank()
                || Figura.equals("")) {
            jButtonANADIR.setEnabled(false);
        } else {
            jButtonANADIR.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelINSTRUCCIONES = new javax.swing.JPanel();
        jLabelINSTRUCCIONES = new javax.swing.JLabel();
        jPanelINTRO = new javax.swing.JPanel();
        jTextFieldPALABRA = new javax.swing.JTextField();
        jLabelPALABRA = new javax.swing.JLabel();
        jLabelSIGNIFICADO = new javax.swing.JLabel();
        jScrollPaneSIGNIFICADO = new javax.swing.JScrollPane();
        jTextAreaSIGNIFICADO = new javax.swing.JTextArea();
        jRadioButtonLINEA = new javax.swing.JRadioButton();
        jLabelLINEA = new javax.swing.JLabel();
        jRadioButtonTERMINAL = new javax.swing.JRadioButton();
        jLabelTERMINAL = new javax.swing.JLabel();
        jRadioButtonPROCESO = new javax.swing.JRadioButton();
        jLabelPROCESO = new javax.swing.JLabel();
        jRadioButtonROMBO = new javax.swing.JRadioButton();
        jLabelROMBO = new javax.swing.JLabel();
        jRadioButtonROMBOIDE = new javax.swing.JRadioButton();
        jLabelROMBOIDE = new javax.swing.JLabel();
        jRadioButtonDOCUMENTO = new javax.swing.JRadioButton();
        jLabelTERMINAL2 = new javax.swing.JLabel();
        jPanelANADIR = new javax.swing.JPanel();
        jButtonANADIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelAPROBADO = new javax.swing.JPanel();
        jLabelRESULTADO = new javax.swing.JLabel();
        jLabelPUNTAJE = new javax.swing.JLabel();
        jButtonAPROBADO = new javax.swing.JButton();
        jPanelRUTA3 = new javax.swing.JPanel();
        jLabelRUTA3 = new javax.swing.JLabel();
        jTextFieldRUTA3 = new javax.swing.JTextField();
        jButtonRUTA3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1061, 681));
        setMinimumSize(new java.awt.Dimension(1061, 681));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1061, 681));

        jPanelINSTRUCCIONES.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etapa 3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabelINSTRUCCIONES.setText("En esta etapa el usuario puede añadir palabras como sugerencias y el significado de la misma., así como la figura de resolución.");

        javax.swing.GroupLayout jPanelINSTRUCCIONESLayout = new javax.swing.GroupLayout(jPanelINSTRUCCIONES);
        jPanelINSTRUCCIONES.setLayout(jPanelINSTRUCCIONESLayout);
        jPanelINSTRUCCIONESLayout.setHorizontalGroup(
            jPanelINSTRUCCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINSTRUCCIONESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelINSTRUCCIONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelINSTRUCCIONESLayout.setVerticalGroup(
            jPanelINSTRUCCIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINSTRUCCIONESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelINSTRUCCIONES)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldPALABRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPALABRAActionPerformed(evt);
            }
        });
        jTextFieldPALABRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPALABRAKeyReleased(evt);
            }
        });

        jLabelPALABRA.setText("Palabra:");

        jLabelSIGNIFICADO.setText("Significado:");

        jTextAreaSIGNIFICADO.setColumns(20);
        jTextAreaSIGNIFICADO.setRows(5);
        jTextAreaSIGNIFICADO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaSIGNIFICADOKeyReleased(evt);
            }
        });
        jScrollPaneSIGNIFICADO.setViewportView(jTextAreaSIGNIFICADO);

        buttonGroup1.add(jRadioButtonLINEA);
        jRadioButtonLINEA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonLINEAMouseClicked(evt);
            }
        });
        jRadioButtonLINEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLINEAActionPerformed(evt);
            }
        });

        jLabelLINEA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Linea.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonTERMINAL);
        jRadioButtonTERMINAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonTERMINALMouseClicked(evt);
            }
        });
        jRadioButtonTERMINAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTERMINALActionPerformed(evt);
            }
        });

        jLabelTERMINAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Terminal.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonPROCESO);
        jRadioButtonPROCESO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonPROCESOMouseClicked(evt);
            }
        });
        jRadioButtonPROCESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPROCESOActionPerformed(evt);
            }
        });

        jLabelPROCESO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proceso.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonROMBO);
        jRadioButtonROMBO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonROMBOMouseClicked(evt);
            }
        });
        jRadioButtonROMBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonROMBOActionPerformed(evt);
            }
        });

        jLabelROMBO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rombo.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonROMBOIDE);
        jRadioButtonROMBOIDE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonROMBOIDEMouseClicked(evt);
            }
        });
        jRadioButtonROMBOIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonROMBOIDEActionPerformed(evt);
            }
        });

        jLabelROMBOIDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Romboide.png"))); // NOI18N

        buttonGroup1.add(jRadioButtonDOCUMENTO);
        jRadioButtonDOCUMENTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDOCUMENTOMouseClicked(evt);
            }
        });
        jRadioButtonDOCUMENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDOCUMENTOActionPerformed(evt);
            }
        });

        jLabelTERMINAL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Documento.png"))); // NOI18N

        javax.swing.GroupLayout jPanelINTROLayout = new javax.swing.GroupLayout(jPanelINTRO);
        jPanelINTRO.setLayout(jPanelINTROLayout);
        jPanelINTROLayout.setHorizontalGroup(
            jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINTROLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSIGNIFICADO)
                    .addComponent(jLabelPALABRA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPALABRA)
                    .addComponent(jScrollPaneSIGNIFICADO, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonLINEA)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLINEA))
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonTERMINAL)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTERMINAL)))
                .addGap(39, 39, 39)
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonROMBO)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelROMBO))
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonPROCESO)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPROCESO)))
                .addGap(40, 40, 40)
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonDOCUMENTO)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTERMINAL2))
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addComponent(jRadioButtonROMBOIDE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelROMBOIDE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelINTROLayout.setVerticalGroup(
            jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINTROLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPALABRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPALABRA))
                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLINEA)
                            .addComponent(jLabelLINEA))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelINTROLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jRadioButtonTERMINAL)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelINTROLayout.createSequentialGroup()
                                .addComponent(jLabelTERMINAL)
                                .addGap(77, 77, 77))))
                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelINTROLayout.createSequentialGroup()
                                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                                        .addComponent(jLabelSIGNIFICADO)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPaneSIGNIFICADO))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelINTROLayout.createSequentialGroup()
                                .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jRadioButtonPROCESO)
                                        .addGap(194, 194, 194))
                                    .addGroup(jPanelINTROLayout.createSequentialGroup()
                                        .addComponent(jLabelPROCESO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelINTROLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonROMBO)
                                                .addGap(27, 27, 27))
                                            .addComponent(jLabelROMBO, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelINTROLayout.createSequentialGroup()
                                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelROMBOIDE)
                                            .addGroup(jPanelINTROLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jRadioButtonROMBOIDE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelINTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelINTROLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonDOCUMENTO)
                                                .addGap(28, 28, 28))
                                            .addComponent(jLabelTERMINAL2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(64, 64, 64))))))
        );

        jPanelANADIR.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jButtonANADIR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonANADIR.setText("Añadir palabra");
        jButtonANADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANADIRActionPerformed(evt);
            }
        });

        jLabel1.setText("Debe llenar los campos de palabra y significado, así como seleccionar una figura para poder añadir una palabra.");

        jLabel2.setText("Puede añadir todas las palabras que desee mientras complete todos los campos.");

        javax.swing.GroupLayout jPanelANADIRLayout = new javax.swing.GroupLayout(jPanelANADIR);
        jPanelANADIR.setLayout(jPanelANADIRLayout);
        jPanelANADIRLayout.setHorizontalGroup(
            jPanelANADIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelANADIRLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButtonANADIR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanelANADIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(85, 85, 85))
        );
        jPanelANADIRLayout.setVerticalGroup(
            jPanelANADIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelANADIRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelANADIRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonANADIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelANADIRLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelAPROBADO.setBackground(new java.awt.Color(102, 255, 0));
        jPanelAPROBADO.setForeground(new java.awt.Color(240, 240, 240));
        jPanelAPROBADO.setMaximumSize(new java.awt.Dimension(367, 60));
        jPanelAPROBADO.setMinimumSize(new java.awt.Dimension(367, 60));

        jLabelRESULTADO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRESULTADO.setText("¡Fase completada con éxito!");

        jLabelPUNTAJE.setText("Tiempo requerido y puntaje.");

        jButtonAPROBADO.setText("Finalizar");
        jButtonAPROBADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPROBADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAPROBADOLayout = new javax.swing.GroupLayout(jPanelAPROBADO);
        jPanelAPROBADO.setLayout(jPanelAPROBADOLayout);
        jPanelAPROBADOLayout.setHorizontalGroup(
            jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRESULTADO)
                    .addComponent(jLabelPUNTAJE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAPROBADO, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAPROBADOLayout.setVerticalGroup(
            jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAPROBADOLayout.createSequentialGroup()
                .addGroup(jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAPROBADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelRESULTADO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPUNTAJE)))
                .addContainerGap())
        );

        jLabelRUTA3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRUTA3.setText("Especificar ruta:");

        jTextFieldRUTA3.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldRUTA3.setText("Pegue la ruta de la ubicación del diccionario aquí...");
        jTextFieldRUTA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRUTA3ActionPerformed(evt);
            }
        });

        jButtonRUTA3.setText("Leer ruta");
        jButtonRUTA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUTA3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRUTA3Layout = new javax.swing.GroupLayout(jPanelRUTA3);
        jPanelRUTA3.setLayout(jPanelRUTA3Layout);
        jPanelRUTA3Layout.setHorizontalGroup(
            jPanelRUTA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRUTA3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRUTA3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRUTA3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRUTA3)
                .addContainerGap())
        );
        jPanelRUTA3Layout.setVerticalGroup(
            jPanelRUTA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRUTA3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRUTA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRUTA3)
                    .addComponent(jTextFieldRUTA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRUTA3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelRUTA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAPROBADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelINSTRUCCIONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelANADIR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelINTRO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelINSTRUCCIONES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelINTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelANADIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanelAPROBADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanelRUTA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLINEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLINEAActionPerformed
        if (jRadioButtonLINEA.isSelected()) {
            Figura = "Linea";
        }
    }//GEN-LAST:event_jRadioButtonLINEAActionPerformed

    private void jRadioButtonPROCESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPROCESOActionPerformed

        if (jRadioButtonPROCESO.isSelected()) {
            Figura = "Proceso";
        }
    }//GEN-LAST:event_jRadioButtonPROCESOActionPerformed

    private void jRadioButtonROMBOIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonROMBOIDEActionPerformed
        if (jRadioButtonROMBOIDE.isSelected()) {
            Figura = "Romboide";
        }
    }//GEN-LAST:event_jRadioButtonROMBOIDEActionPerformed

    private void jButtonANADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANADIRActionPerformed
        try {
            String Informacion = "";
            try {
                BufferedReader bf = new BufferedReader(new FileReader(Ruta));
                Informacion = bf.readLine();
                Informacion = Informacion + jTextFieldPALABRA.getText()
                        + ":; " + Figura + ":; "
                        + jTextAreaSIGNIFICADO.getText() + ":; ";
                PrintWriter writer = new PrintWriter(Ruta, "UTF-8");
                writer.print(Informacion);
                writer.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error leyendo el archivo: " + e);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tiempo2 = System.currentTimeMillis();
        jLabelPUNTAJE.setText("Etapa concluida en "
                + (((tiempo2 - tiempo1) / 36000000) + " horas, "
                + (((tiempo2 - tiempo1) / 60000) % 60) + " minutos y "
                + ((tiempo2 - tiempo1) / 1000) % 60) + " segundos.");

        jPanelAPROBADO.setVisible(true);
    }//GEN-LAST:event_jButtonANADIRActionPerformed

    private void jRadioButtonTERMINALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTERMINALActionPerformed
        if (jRadioButtonTERMINAL.isSelected()) {
            Figura = "Terminal";
        }
    }//GEN-LAST:event_jRadioButtonTERMINALActionPerformed

    private void jRadioButtonROMBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonROMBOActionPerformed
        if (jRadioButtonROMBO.isSelected()) {
            Figura = "Rombo";
        }
    }//GEN-LAST:event_jRadioButtonROMBOActionPerformed

    private void jRadioButtonDOCUMENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDOCUMENTOActionPerformed
        if (jRadioButtonDOCUMENTO.isSelected()) {
            Figura = "Documento";
        }
    }//GEN-LAST:event_jRadioButtonDOCUMENTOActionPerformed

    private void jTextFieldPALABRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPALABRAActionPerformed

    }//GEN-LAST:event_jTextFieldPALABRAActionPerformed

    private void jTextAreaSIGNIFICADOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaSIGNIFICADOKeyReleased
        Validar();
    }//GEN-LAST:event_jTextAreaSIGNIFICADOKeyReleased

    private void jTextFieldPALABRAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPALABRAKeyReleased
        Validar();
    }//GEN-LAST:event_jTextFieldPALABRAKeyReleased

    private void jRadioButtonLINEAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonLINEAMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonLINEAMouseClicked

    private void jRadioButtonTERMINALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonTERMINALMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonTERMINALMouseClicked

    private void jRadioButtonPROCESOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonPROCESOMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonPROCESOMouseClicked

    private void jRadioButtonROMBOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonROMBOMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonROMBOMouseClicked

    private void jRadioButtonROMBOIDEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonROMBOIDEMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonROMBOIDEMouseClicked

    private void jRadioButtonDOCUMENTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDOCUMENTOMouseClicked
        Validar();
    }//GEN-LAST:event_jRadioButtonDOCUMENTOMouseClicked

    private void jButtonAPROBADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPROBADOActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAPROBADOActionPerformed

    private void jTextFieldRUTA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRUTA3ActionPerformed
        if (jTextFieldRUTA.equals("Pegue la ruta de la ubicación del diccionario aquí..."));
        {
            jTextFieldRUTA.setText("");
        }
    }//GEN-LAST:event_jTextFieldRUTA3ActionPerformed

    private void jButtonRUTA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRUTA3ActionPerformed
        try {
            Ruta = jTextFieldRUTA3.getText();
            Ruta = Ruta + "\\PalabrasClave.txt";
            jButtonANADIR.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error leyendo el archivo: " + e);
        }
    }//GEN-LAST:event_jButtonRUTA3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonANADIR;
    private javax.swing.JButton jButtonAPROBADO;
    private javax.swing.JButton jButtonRUTA;
    private javax.swing.JButton jButtonRUTA1;
    private javax.swing.JButton jButtonRUTA2;
    private javax.swing.JButton jButtonRUTA3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelINSTRUCCIONES;
    private javax.swing.JLabel jLabelLINEA;
    private javax.swing.JLabel jLabelPALABRA;
    private javax.swing.JLabel jLabelPROCESO;
    private javax.swing.JLabel jLabelPUNTAJE;
    private javax.swing.JLabel jLabelRESULTADO;
    private javax.swing.JLabel jLabelROMBO;
    private javax.swing.JLabel jLabelROMBOIDE;
    private javax.swing.JLabel jLabelRUTA;
    private javax.swing.JLabel jLabelRUTA1;
    private javax.swing.JLabel jLabelRUTA2;
    private javax.swing.JLabel jLabelRUTA3;
    private javax.swing.JLabel jLabelSIGNIFICADO;
    private javax.swing.JLabel jLabelTERMINAL;
    private javax.swing.JLabel jLabelTERMINAL2;
    private javax.swing.JPanel jPanelANADIR;
    private javax.swing.JPanel jPanelAPROBADO;
    private javax.swing.JPanel jPanelINSTRUCCIONES;
    private javax.swing.JPanel jPanelINTRO;
    private javax.swing.JPanel jPanelRUTA;
    private javax.swing.JPanel jPanelRUTA1;
    private javax.swing.JPanel jPanelRUTA2;
    private javax.swing.JPanel jPanelRUTA3;
    private javax.swing.JRadioButton jRadioButtonDOCUMENTO;
    private javax.swing.JRadioButton jRadioButtonLINEA;
    private javax.swing.JRadioButton jRadioButtonPROCESO;
    private javax.swing.JRadioButton jRadioButtonROMBO;
    private javax.swing.JRadioButton jRadioButtonROMBOIDE;
    private javax.swing.JRadioButton jRadioButtonTERMINAL;
    private javax.swing.JScrollPane jScrollPaneSIGNIFICADO;
    private javax.swing.JTextArea jTextAreaSIGNIFICADO;
    private javax.swing.JTextField jTextFieldPALABRA;
    private javax.swing.JTextField jTextFieldRUTA;
    private javax.swing.JTextField jTextFieldRUTA1;
    private javax.swing.JTextField jTextFieldRUTA2;
    private javax.swing.JTextField jTextFieldRUTA3;
    // End of variables declaration//GEN-END:variables
}
