package proyectoprogra1;

import java.awt.Color;
import java.time.Duration;

public class Problema1 extends javax.swing.JFrame {

    int puntos = 0;
    long tiempo1;
    long tiempo2;

    public Problema1() {
        initComponents();
        jPanelIMAGEN.setVisible(false);
        jPanelAPROBADO.setVisible(false);
        jPanelB.setVisible(false);
        jPanelC.setVisible(false);
        jPanelD.setVisible(false);
        jPanelE.setVisible(false);
        tiempo1 = System.currentTimeMillis();
        for (long i = 0; i <= 100000; i++) {
            continue;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupA = new javax.swing.ButtonGroup();
        buttonGroupB = new javax.swing.ButtonGroup();
        buttonGroupC = new javax.swing.ButtonGroup();
        buttonGroupD = new javax.swing.ButtonGroup();
        buttonGroupE = new javax.swing.ButtonGroup();
        jPanelTITULO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelA = new javax.swing.JPanel();
        jRadioButtonA1 = new javax.swing.JRadioButton();
        jRadioButtonA2 = new javax.swing.JRadioButton();
        jRadioButtonA3 = new javax.swing.JRadioButton();
        jButtonA = new javax.swing.JButton();
        jPanelB = new javax.swing.JPanel();
        jRadioButtonB1 = new javax.swing.JRadioButton();
        jRadioButtonB2 = new javax.swing.JRadioButton();
        jRadioButtonB3 = new javax.swing.JRadioButton();
        jButtonB = new javax.swing.JButton();
        jPanelC = new javax.swing.JPanel();
        jRadioButtonC1 = new javax.swing.JRadioButton();
        jRadioButtonC2 = new javax.swing.JRadioButton();
        jRadioButtonC3 = new javax.swing.JRadioButton();
        jButtonC = new javax.swing.JButton();
        jPanelD = new javax.swing.JPanel();
        jRadioButtonD1 = new javax.swing.JRadioButton();
        jRadioButtonD2 = new javax.swing.JRadioButton();
        jRadioButtonD3 = new javax.swing.JRadioButton();
        jButtonD = new javax.swing.JButton();
        jPanelE = new javax.swing.JPanel();
        jRadioButtonE1 = new javax.swing.JRadioButton();
        jRadioButtonE2 = new javax.swing.JRadioButton();
        jRadioButtonE3 = new javax.swing.JRadioButton();
        jButtonE = new javax.swing.JButton();
        jPanelIMAGEN = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelIMAGEN = new javax.swing.JLabel();
        jPanelAPROBADO = new javax.swing.JPanel();
        jLabelRESULTADO = new javax.swing.JLabel();
        jLabelPUNTAJE = new javax.swing.JLabel();
        jButtonAPROBADO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1061, 681));
        setMinimumSize(new java.awt.Dimension(1061, 681));
        setUndecorated(true);
        setResizable(false);

        jPanelTITULO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Etapa 1 - Problema 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanelTITULO.setMaximumSize(new java.awt.Dimension(650, 85));
        jPanelTITULO.setMinimumSize(new java.awt.Dimension(650, 85));
        jPanelTITULO.setPreferredSize(new java.awt.Dimension(650, 85));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Planteo: El programa consiste en una sumadora. El usuario debe digitar ambos sumandos y decidir si desea");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("realizar una nueva operación con un \"Sí\" o salir del programa con cualquier otra palabra.");

        javax.swing.GroupLayout jPanelTITULOLayout = new javax.swing.GroupLayout(jPanelTITULO);
        jPanelTITULO.setLayout(jPanelTITULOLayout);
        jPanelTITULOLayout.setHorizontalGroup(
            jPanelTITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTITULOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelTITULOLayout.setVerticalGroup(
            jPanelTITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTITULOLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanelA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "A) ¿Con cuántas variables de tipo integer inicializaremos nuestro programa?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanelA.setMaximumSize(new java.awt.Dimension(650, 110));
        jPanelA.setMinimumSize(new java.awt.Dimension(650, 110));
        jPanelA.setPreferredSize(new java.awt.Dimension(650, 110));

        buttonGroupA.add(jRadioButtonA1);
        jRadioButtonA1.setText("No es necesario inicializar variables de tipo Integer.");
        jRadioButtonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonA1ActionPerformed(evt);
            }
        });

        buttonGroupA.add(jRadioButtonA2);
        jRadioButtonA2.setText("Con 1 basta.");
        jRadioButtonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonA2ActionPerformed(evt);
            }
        });

        buttonGroupA.add(jRadioButtonA3);
        jRadioButtonA3.setText("Se necesitan al menos 2.");

        jButtonA.setText("Revisar");
        jButtonA.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonA.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonA.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelALayout = new javax.swing.GroupLayout(jPanelA);
        jPanelA.setLayout(jPanelALayout);
        jPanelALayout.setHorizontalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addComponent(jRadioButtonA1)
                        .addGap(0, 351, Short.MAX_VALUE))
                    .addGroup(jPanelALayout.createSequentialGroup()
                        .addGroup(jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonA2)
                            .addComponent(jRadioButtonA3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelALayout.setVerticalGroup(
            jPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonA3)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "B) ¿Con cuántas variables de tipo string inicializaremos nuestro programa?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanelB.setMaximumSize(new java.awt.Dimension(650, 110));
        jPanelB.setMinimumSize(new java.awt.Dimension(650, 110));
        jPanelB.setPreferredSize(new java.awt.Dimension(650, 110));

        buttonGroupB.add(jRadioButtonB1);
        jRadioButtonB1.setText("No es necesario inicializar variables de tipo String.");
        jRadioButtonB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB1ActionPerformed(evt);
            }
        });

        buttonGroupB.add(jRadioButtonB2);
        jRadioButtonB2.setText("Con 1 basta.");
        jRadioButtonB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonB2ActionPerformed(evt);
            }
        });

        buttonGroupB.add(jRadioButtonB3);
        jRadioButtonB3.setText("Se necesitan al menos 2.");

        jButtonB.setText("Revisar");
        jButtonB.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonB.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonB.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBLayout = new javax.swing.GroupLayout(jPanelB);
        jPanelB.setLayout(jPanelBLayout);
        jPanelBLayout.setHorizontalGroup(
            jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBLayout.createSequentialGroup()
                        .addComponent(jRadioButtonB1)
                        .addGap(0, 359, Short.MAX_VALUE))
                    .addGroup(jPanelBLayout.createSequentialGroup()
                        .addGroup(jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonB2)
                            .addComponent(jRadioButtonB3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBLayout.setVerticalGroup(
            jPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonB3)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C) Si la variable Q guarda el string que digita el usuario, ¿cual es un posible valor de Q para que el programa ejecute la suma?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanelC.setMaximumSize(new java.awt.Dimension(650, 110));
        jPanelC.setMinimumSize(new java.awt.Dimension(650, 110));
        jPanelC.setPreferredSize(new java.awt.Dimension(650, 110));

        buttonGroupC.add(jRadioButtonC1);
        jRadioButtonC1.setText("1");
        jRadioButtonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonC1ActionPerformed(evt);
            }
        });

        buttonGroupC.add(jRadioButtonC2);
        jRadioButtonC2.setText("True");
        jRadioButtonC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonC2ActionPerformed(evt);
            }
        });

        buttonGroupC.add(jRadioButtonC3);
        jRadioButtonC3.setText("\"Si\"");

        jButtonC.setText("Revisar");
        jButtonC.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonC.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonC.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCLayout = new javax.swing.GroupLayout(jPanelC);
        jPanelC.setLayout(jPanelCLayout);
        jPanelCLayout.setHorizontalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCLayout.createSequentialGroup()
                        .addComponent(jRadioButtonC1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCLayout.createSequentialGroup()
                        .addGroup(jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonC2)
                            .addComponent(jRadioButtonC3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelCLayout.setVerticalGroup(
            jPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonC3)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "D) ¿Qué sentencia de Output utilizarías para mostrar la suma al usuario?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanelD.setMaximumSize(new java.awt.Dimension(650, 110));
        jPanelD.setMinimumSize(new java.awt.Dimension(650, 110));
        jPanelD.setName(""); // NOI18N
        jPanelD.setPreferredSize(new java.awt.Dimension(650, 110));

        buttonGroupD.add(jRadioButtonD1);
        jRadioButtonD1.setText("\"El resultado de la suma es \"+(A+B)");
        jRadioButtonD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonD1ActionPerformed(evt);
            }
        });

        buttonGroupD.add(jRadioButtonD2);
        jRadioButtonD2.setText("\"El resultado de la suma es \"(A+B)");
        jRadioButtonD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonD2ActionPerformed(evt);
            }
        });

        buttonGroupD.add(jRadioButtonD3);
        jRadioButtonD3.setText("\"El resultado de la suma es +(A+B)\"");

        jButtonD.setText("Revisar");
        jButtonD.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonD.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonD.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDLayout = new javax.swing.GroupLayout(jPanelD);
        jPanelD.setLayout(jPanelDLayout);
        jPanelDLayout.setHorizontalGroup(
            jPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDLayout.createSequentialGroup()
                        .addComponent(jRadioButtonD1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDLayout.createSequentialGroup()
                        .addGroup(jPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonD2)
                            .addComponent(jRadioButtonD3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDLayout.setVerticalGroup(
            jPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonD3)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E) ¿Cuántas validaciones han sido necesarias de programar en esta sumadora?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanelE.setMaximumSize(new java.awt.Dimension(650, 110));
        jPanelE.setMinimumSize(new java.awt.Dimension(650, 110));
        jPanelE.setPreferredSize(new java.awt.Dimension(650, 110));

        buttonGroupE.add(jRadioButtonE1);
        jRadioButtonE1.setText("Cero.");
        jRadioButtonE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonE1ActionPerformed(evt);
            }
        });

        buttonGroupE.add(jRadioButtonE2);
        jRadioButtonE2.setText("Una.");
        jRadioButtonE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonE2ActionPerformed(evt);
            }
        });

        buttonGroupE.add(jRadioButtonE3);
        jRadioButtonE3.setText("Dos.");

        jButtonE.setText("Revisar");
        jButtonE.setMaximumSize(new java.awt.Dimension(100, 23));
        jButtonE.setMinimumSize(new java.awt.Dimension(100, 23));
        jButtonE.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelELayout = new javax.swing.GroupLayout(jPanelE);
        jPanelE.setLayout(jPanelELayout);
        jPanelELayout.setHorizontalGroup(
            jPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelELayout.createSequentialGroup()
                        .addComponent(jRadioButtonE1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelELayout.createSequentialGroup()
                        .addGroup(jPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonE2)
                            .addComponent(jRadioButtonE3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                        .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelELayout.setVerticalGroup(
            jPanelELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonE2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonE3)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelIMAGEN.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelIMAGEN.setMaximumSize(new java.awt.Dimension(367, 524));
        jPanelIMAGEN.setMinimumSize(new java.awt.Dimension(367, 524));
        jPanelIMAGEN.setPreferredSize(new java.awt.Dimension(367, 524));

        jLabelIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Problema1.PNG"))); // NOI18N
        jScrollPane1.setViewportView(jLabelIMAGEN);

        javax.swing.GroupLayout jPanelIMAGENLayout = new javax.swing.GroupLayout(jPanelIMAGEN);
        jPanelIMAGEN.setLayout(jPanelIMAGENLayout);
        jPanelIMAGENLayout.setHorizontalGroup(
            jPanelIMAGENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jPanelIMAGENLayout.setVerticalGroup(
            jPanelIMAGENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelAPROBADO.setBackground(new java.awt.Color(102, 255, 0));
        jPanelAPROBADO.setForeground(new java.awt.Color(240, 240, 240));
        jPanelAPROBADO.setMaximumSize(new java.awt.Dimension(367, 60));
        jPanelAPROBADO.setMinimumSize(new java.awt.Dimension(367, 60));
        jPanelAPROBADO.setPreferredSize(new java.awt.Dimension(367, 60));

        jLabelRESULTADO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRESULTADO.setText("¡Fase completada con éxito!");

        jLabelPUNTAJE.setText("Tiempo requerido y puntaje.");

        jButtonAPROBADO.setText("A Etapa 2");
        jButtonAPROBADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPROBADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAPROBADOLayout = new javax.swing.GroupLayout(jPanelAPROBADO);
        jPanelAPROBADO.setLayout(jPanelAPROBADOLayout);
        jPanelAPROBADOLayout.setHorizontalGroup(
            jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRESULTADO)
                    .addComponent(jLabelPUNTAJE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAPROBADO, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAPROBADOLayout.setVerticalGroup(
            jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                .addGroup(jPanelAPROBADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelRESULTADO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPUNTAJE))
                    .addGroup(jPanelAPROBADOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAPROBADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelAPROBADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelIMAGEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelAPROBADO, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelIMAGEN, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonA1ActionPerformed

    }//GEN-LAST:event_jRadioButtonA1ActionPerformed

    private void jRadioButtonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonA2ActionPerformed

    }//GEN-LAST:event_jRadioButtonA2ActionPerformed

    private void jRadioButtonB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB1ActionPerformed

    }//GEN-LAST:event_jRadioButtonB1ActionPerformed

    private void jRadioButtonB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonB2ActionPerformed

    }//GEN-LAST:event_jRadioButtonB2ActionPerformed

    private void jRadioButtonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonC1ActionPerformed

    private void jRadioButtonC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonC2ActionPerformed

    private void jRadioButtonD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonD1ActionPerformed

    private void jRadioButtonD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonD2ActionPerformed

    private void jRadioButtonE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonE1ActionPerformed

    private void jRadioButtonE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonE2ActionPerformed

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        if (jRadioButtonA1.isSelected()) {
            jButtonA.setForeground(Color.RED);
            jButtonA.setText("¡Incorrecta!");
            jButtonA.setEnabled(false);
            jPanelB.setVisible(true);

        }
        if (jRadioButtonA2.isSelected()) {
            jButtonA.setForeground(Color.RED);
            jButtonA.setText("¡Incorrecta!");
            jButtonA.setEnabled(false);
            jPanelB.setVisible(true);

        }
        if (jRadioButtonA3.isSelected()) {
            jButtonA.setForeground(Color.GREEN);
            jButtonA.setText("¡Correcta!");
            jButtonA.setEnabled(false);
            puntos++;
            jPanelB.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        if (jRadioButtonB1.isSelected()) {
            jButtonB.setForeground(Color.RED);
            jButtonB.setText("¡Incorrecta!");
            jButtonB.setEnabled(false);
            jPanelC.setVisible(true);

        }
        if (jRadioButtonB3.isSelected()) {
            jButtonB.setForeground(Color.RED);
            jButtonB.setText("¡Incorrecta!");
            jButtonB.setEnabled(false);
            jPanelC.setVisible(true);

        }
        if (jRadioButtonB2.isSelected()) {
            jButtonB.setForeground(Color.GREEN);
            jButtonB.setText("¡Correcta!");
            jButtonB.setEnabled(false);
            puntos++;
            jPanelC.setVisible(true);
        }
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        if (jRadioButtonC1.isSelected()) {
            jButtonC.setForeground(Color.RED);
            jButtonC.setText("¡Incorrecta!");
            jButtonC.setEnabled(false);
            jPanelD.setVisible(true);

        }
        if (jRadioButtonC2.isSelected()) {
            jButtonC.setForeground(Color.RED);
            jButtonC.setText("¡Incorrecta!");
            jButtonC.setEnabled(false);
            jPanelD.setVisible(true);

        }
        if (jRadioButtonC3.isSelected()) {
            jButtonC.setForeground(Color.GREEN);
            jButtonC.setText("¡Correcta!");
            jButtonC.setEnabled(false);
            puntos++;
            jPanelD.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        if (jRadioButtonD3.isSelected()) {
            jButtonD.setForeground(Color.RED);
            jButtonD.setText("¡Incorrecta!");
            jButtonD.setEnabled(false);
            jPanelE.setVisible(true);

        }
        if (jRadioButtonD2.isSelected()) {
            jButtonD.setForeground(Color.RED);
            jButtonD.setText("¡Incorrecta!");
            jButtonD.setEnabled(false);
            jPanelE.setVisible(true);

        }
        if (jRadioButtonD1.isSelected()) {
            jButtonD.setForeground(Color.GREEN);
            jButtonD.setText("¡Correcta!");
            jButtonD.setEnabled(false);
            puntos++;
            jPanelE.setVisible(true);
        }
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        if (jRadioButtonE3.isSelected()) {
            jButtonE.setForeground(Color.RED);
            jButtonE.setText("¡Incorrecta!");
            jButtonE.setEnabled(false);
            jPanelAPROBADO.setVisible(true);

        }
        if (jRadioButtonE2.isSelected()) {
            jButtonE.setForeground(Color.RED);
            jButtonE.setText("¡Incorrecta!");
            jButtonE.setEnabled(false);
            jPanelAPROBADO.setVisible(true);

        }
        if (jRadioButtonE1.isSelected()) {
            jButtonE.setForeground(Color.GREEN);
            jButtonE.setText("¡Correcta!");
            jButtonE.setEnabled(false);
            puntos++;
            jPanelAPROBADO.setVisible(true);
        }
        if (puntos < 3) {
            jPanelAPROBADO.setBackground(new java.awt.Color(255, 51, 51));
            jButtonAPROBADO.setText("Reintentar");
            jLabelRESULTADO.setText("Intento fallido");
            tiempo2 = System.currentTimeMillis();
            jPanelIMAGEN.setVisible(true);
            jLabelPUNTAJE.setText(puntos + " puntos en "
                    + (((tiempo2 - tiempo1) / 36000000) + " horas, "
                    + (((tiempo2 - tiempo1) / 60000) % 60) + " minutos y "
                    + ((tiempo2 - tiempo1) / 1000) % 60) + " segundos.");
        }
        if (puntos >= 3) {
            tiempo2 = System.currentTimeMillis();
            jPanelIMAGEN.setVisible(true);
            jLabelPUNTAJE.setText(puntos + " puntos en "
                    + (((tiempo2 - tiempo1) / 36000000) + " horas, "
                    + (((tiempo2 - tiempo1) / 60000) % 60) + " minutos y "
                    + ((tiempo2 - tiempo1) / 1000) % 60) + " segundos.");
        }
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonAPROBADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPROBADOActionPerformed
        if (puntos < 3) {
            Juego1 juego1 = new Juego1();
            dispose();

        } else {
            Juego2 juego2 = new Juego2();
            dispose();
            juego2.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAPROBADOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupA;
    private javax.swing.ButtonGroup buttonGroupB;
    private javax.swing.ButtonGroup buttonGroupC;
    private javax.swing.ButtonGroup buttonGroupD;
    private javax.swing.ButtonGroup buttonGroupE;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonAPROBADO;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelIMAGEN;
    private javax.swing.JLabel jLabelPUNTAJE;
    private javax.swing.JLabel jLabelRESULTADO;
    private javax.swing.JPanel jPanelA;
    private javax.swing.JPanel jPanelAPROBADO;
    private javax.swing.JPanel jPanelB;
    private javax.swing.JPanel jPanelC;
    private javax.swing.JPanel jPanelD;
    private javax.swing.JPanel jPanelE;
    private javax.swing.JPanel jPanelIMAGEN;
    private javax.swing.JPanel jPanelTITULO;
    private javax.swing.JRadioButton jRadioButtonA1;
    private javax.swing.JRadioButton jRadioButtonA2;
    private javax.swing.JRadioButton jRadioButtonA3;
    private javax.swing.JRadioButton jRadioButtonB1;
    private javax.swing.JRadioButton jRadioButtonB2;
    private javax.swing.JRadioButton jRadioButtonB3;
    private javax.swing.JRadioButton jRadioButtonC1;
    private javax.swing.JRadioButton jRadioButtonC2;
    private javax.swing.JRadioButton jRadioButtonC3;
    private javax.swing.JRadioButton jRadioButtonD1;
    private javax.swing.JRadioButton jRadioButtonD2;
    private javax.swing.JRadioButton jRadioButtonD3;
    private javax.swing.JRadioButton jRadioButtonE1;
    private javax.swing.JRadioButton jRadioButtonE2;
    private javax.swing.JRadioButton jRadioButtonE3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
