package proyectoprogra1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.Timer;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;

public class Temporizador extends javax.swing.JFrame {
    
    int transcurrido = 0, segundos = 0, minutos = 0, horas = 0;
    boolean iniciado = false;
    String Segundos = String.format("%02d", segundos);
    String Minutos = String.format("%02d", minutos);
    String Horas = String.format("%02d", horas);    

    Timer timer = new Timer(1000, new ActionListener() {

        public void actionPerformed(ActionEvent e) {

            transcurrido = transcurrido + 1000;
            horas = transcurrido / 3600000;
            minutos = (transcurrido / 60000) % 60;
            segundos = (transcurrido / 1000) % 60;
            String Segundos = String.format("%02d", segundos);
            String Minutos = String.format("%02d", minutos);
            String Horas = String.format("%02d", horas);
            jLabelHORAS.setText(Horas);
            jLabelMINUTOS.setText(Minutos);
            jLabelSEGUNDOS.setText(Segundos);
        }

    });

    Temporizador() {
        initComponents();
        Comienzo();

    }

    public void actionPerformed(ActionEvent e) {
        timer.start();
    }

    private void Comienzo() {
        String Informacion = "";
        
        
        try {
            BufferedReader bf = new BufferedReader (new FileReader("C:\\Users\\felix\\Documents\\proyecto.txt"));
            Informacion = bf.readLine();
            String[] Dato = Informacion.split(" - ");
            jLabelTITULO.setText("Temporizador - "+Dato[0]);
            jLabelJUGADOR.setText(Dato[1]+" está jugando.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error leyendo el archivo: "+e);
        }        
        setVisible(true);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRENDIRSE = new javax.swing.JButton();
        jLabelTITULO = new javax.swing.JLabel();
        jLabelNOTA1 = new javax.swing.JLabel();
        jLabelHORAS = new javax.swing.JLabel();
        jLabelNOTAhoras = new javax.swing.JLabel();
        jLabelMINUTOS = new javax.swing.JLabel();
        jLabelNOTAminutos = new javax.swing.JLabel();
        jLabelSEGUNDOS = new javax.swing.JLabel();
        jLabelNOTAsegundos = new javax.swing.JLabel();
        jLabelJUGADOR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tiempo");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(1060, 0));
        setMaximumSize(new java.awt.Dimension(235, 175));
        setMinimumSize(new java.awt.Dimension(235, 175));
        setName("jFrameTEMPO"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(235, 175));
        setResizable(false);

        jButtonRENDIRSE.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jButtonRENDIRSE.setText("¡Rendirte!");
        jButtonRENDIRSE.setToolTipText("");
        jButtonRENDIRSE.setAlignmentY(0.0F);
        jButtonRENDIRSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRENDIRSEActionPerformed(evt);
            }
        });

        jLabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTITULO.setText("Temporizador - Etapa X");

        jLabelNOTA1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelNOTA1.setText("Presiona ¡Rendirte! para acabar tu intento");

        jLabelHORAS.setFont(new java.awt.Font("Calculator", 1, 30)); // NOI18N
        jLabelHORAS.setText("00");

        jLabelNOTAhoras.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelNOTAhoras.setText("horas");

        jLabelMINUTOS.setFont(new java.awt.Font("Calculator", 1, 30)); // NOI18N
        jLabelMINUTOS.setText("00");

        jLabelNOTAminutos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelNOTAminutos.setText("minutos");

        jLabelSEGUNDOS.setFont(new java.awt.Font("Calculator", 1, 30)); // NOI18N
        jLabelSEGUNDOS.setText("00");

        jLabelNOTAsegundos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabelNOTAsegundos.setText("segundos");

        jLabelJUGADOR.setText("XXX está jugando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNOTA1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelTITULO)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRENDIRSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHORAS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNOTAhoras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMINUTOS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNOTAminutos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSEGUNDOS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNOTAsegundos))
                            .addComponent(jLabelJUGADOR))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNOTA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHORAS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNOTAhoras)
                    .addComponent(jLabelMINUTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNOTAminutos)
                    .addComponent(jLabelSEGUNDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNOTAsegundos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRENDIRSE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJUGADOR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRENDIRSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRENDIRSEActionPerformed
//        String Informacion;
//        try {
//            BufferedReader bf = new BufferedReader(new FileReader("C:\\Users\\felix\\Documents\\proyecto.txt"));
//            Informacion = bf.readLine();
//            String[] Dato = Informacion.split(" - ");
//            String to = Dato[3];
//            final String username = "felixjb13@gmail.com";
//            final String password = "CONTRASEÑA";
//
//            Properties prop = new Properties();
//            prop.put("mail.smtp.host", "smtp.gmail.com");
//            prop.put("mail.smtp.port", "587");
//            prop.put("mail.smtp.auth", "true");
//            prop.put("mail.smtp.starttls.enable", "true"); //TLS
//
//            Session session = Session.getInstance(prop,
//                    new javax.mail.Authenticator() {
//                protected PasswordAuthentication getPasswordAuthentication() {
//                    return new PasswordAuthentication(username, password);
//                }
//            });
//            try {
//                Message message = new MimeMessage(session);
//                message.setFrom(new InternetAddress("felixjb13@gmail.com"));
//                message.setRecipients(
//                        Message.RecipientType.TO,
//                        InternetAddress.parse(Dato[3])
//                );
//                message.setSubject("Resultados Analizador de Lógica para Informáticos");
//                message.setText("Hola," + Dato[1]
//                        + "\n\n Usted ha participado del juego \"Analizador de lógica para informáticos\"."
//                        + "\n\n Logró superar la etapa X en un tiempo de " + Horas + " horas, " + Minutos + " minutos y " + Segundos + " segundos."
//                        + "\n\n Muchas gracias por participar");
//                Transport.send(message);
//                System.out.println("Correo enviado a "+Dato[3]);
//            } catch (MessagingException e) {
//                e.printStackTrace();
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error enviando el correo: " + e);
//        }
            System.exit(0);

    }//GEN-LAST:event_jButtonRENDIRSEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRENDIRSE;
    private javax.swing.JLabel jLabelHORAS;
    private javax.swing.JLabel jLabelJUGADOR;
    private javax.swing.JLabel jLabelMINUTOS;
    private javax.swing.JLabel jLabelNOTA1;
    private javax.swing.JLabel jLabelNOTAhoras;
    private javax.swing.JLabel jLabelNOTAminutos;
    private javax.swing.JLabel jLabelNOTAsegundos;
    private javax.swing.JLabel jLabelSEGUNDOS;
    private javax.swing.JLabel jLabelTITULO;
    // End of variables declaration//GEN-END:variables
}
